import { Inter } from 'next/font/google';
import '../styles/globals.scss';
import StoreProvider from './StoreProvider';
import ClientSideAuth from './login/ClientSideAuth';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Cocktail',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body className={inter.className}>
        <StoreProvider>
          <ClientSideAuth>{children}</ClientSideAuth>
        </StoreProvider>
      </body>
    </html>
  );
}
