import { Inter } from 'next/font/google';
import '../styles/globals.css';
import StoreProvider from './StoreProvider';
import ClientSideAuth from './ClientSideAuth';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  const initialReduxState = {
    user: {
      isAuthenticated: false,
    },
  };

  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body className={inter.className}>
        <StoreProvider initialReduxState={initialReduxState}>
          <ClientSideAuth>{children}</ClientSideAuth>
        </StoreProvider>
      </body>
    </html>
  );
}
