'use client';
import { Inter } from 'next/font/google';

import StoreProvider from './StoreProvider';

import LayoutContent from './LayoutContent';
import '../styles/globals.scss';

const inter = Inter({ subsets: ['latin'] });

const metadata = {
  title: 'Cocktail',
  description: 'Generated by create next app',
};

const Layout = ({ children }) => {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body className={inter.className}>
          <StoreProvider>
            <LayoutContent>{children}</LayoutContent>
          </StoreProvider>
      </body>
    </html>
  );
};

export default Layout;
